Bookers2nd/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :books
  resources :users
  resources :home, only: [:index]
  get "home/about" => "home#about"
end

Bookers2nd/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true,
		length: {maximum:200}
end

Bookers2nd/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
  	@book = Book.new 
    @user = User.all
  	@books = Book.all
    @user = current_user
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
    @user = current_user
    @books = Book.all
  	if @book.save
       flash[:notice]
  	   redirect_to book_path(@book.id), notice: "You have creatad book successfully."
    else
      render :index
    end
  end

  def show
  	@book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book =Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]
      redirect_to book_path(@book.id),notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

Bookers2nd/app/helpers/books_helper.rb
module BooksHelper
end

Bookers2nd/app/views/books/_footer.html.erb
<div class="container pl-15 pr-15">
	<div class="row">
		<div class="col-xs-3 col-xs-offset-9">
			<p>CopyRight Infratop.inc</p>
		</div>
	</div>
</div>


Bookers2nd/app/views/books/_header.html.erb
<nav class="nav navbar-inverse pl-15 pr-15">
	<nav class="nav navbar-nav navbar-left">
		<span class="text-white">Bookers</span>
	</nav>
	<ul class="nav navbar-nav navbar-right ">

		  	<% if user_signed_in? %>
			<li class="p-15">
				<%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home"  %>
			</li>

			<li class="p-15">
				<%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %>
			</li>

			<li class="p-15">
				<%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %>
			</li>

			<li class="p-15">
				<%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
			</li>



			<% else %>
			<li class="p-15">
				 <%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %>
			</li>

			<li class="p-15">
				<%= link_to " About", home_about_path, class: "glyphicon glyphicon-link"  %>
			</li>

			<li class="p-15">
			  	<%= link_to " Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
			</li>

			<li class="p-15">
			  	<%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
			</li>



	</ul>
   	<%end%>
</nav>


Bookers2nd/app/views/books/_sidebar.html.erb

<div class="col-xs-3">
	<h3>User info</h3>
	<%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
		<table class="table">
			<tbody>
				<tr>
					<th>name</th>
					<th><%= user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= user.introduction %></th>
				</tr>
			</tbody>
		</table>
		<div class="row">
			<div class="col-xs-12 btn btn-default ">
				<%= link_to "", edit_user_path(user.id), class: "glyphicon glyphicon-wrench" %>
			</div>
		</div>
		<h2>New book</h2>
		<!-- form_for部分 -->
		<%= form_for(book) do |f| %>
			<div class="field row">
				<label for="book_title">Title</label>
				<%= f.text_field :title, class: "col-xs-12" %>
			</div>
			<div class="field row">
				<h4>Opinion</h4>
				<%= f.text_area :body, class: "col-xs-12" %>
			</div>
			<div class="actions row">
				<br><%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %></br>
			</div>
		<% end %>
</div>

Bookers2nd/app/views/books/edit.html.erb
<%= render "books/header", books: @user %>
<div class="container pl-15 pr-15">
<p id="notice"><%= notice %></p>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>

			<% if @book.errors.any? %>
		  <div id="error_explanation" class="alert alert-danger">
		    <ul>
		    	<%= @book.errors.count %>errors prohibited this obj from being saved:
		      <% @book.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>

			<%= form_for(@book) do |books| %>
			<h4>Title</h4>
			<%= books.text_field :title, class: "col-xs-12" %>
			<h4>Opinion</h4>
			<%= books.text_area :body, class: "col-xs-12" %>
			<%= books.submit "Update Book", class: "btn btn-primary col-xs-12" %>
			<% end %>
			<%= link_to "Show", book_path(@book.id) %>|
			<%= link_to "Back", books_path %>
		</div>
	</div>
</div>
<%= render "books/footer" %>

Bookers2nd/app/views/books/index.html.erb
<%= render "books/header", books: @user %>
	<div class="container pl-15 pr-15">
		<% if @book.errors.any? %>
		    <div id="error_explanation" class="alert alert-danger">
			    <ul> 
			    	<%= @book.errors.count %>errors prohibited this obj from being saved:
			      	<% @book.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			</div>
		<% end %>



	<p id="notice"><%= notice %></p>
		<div class="row">
			<%= render "books/sidebar", book: @book,user: @user %>
			<h3>Books</h3>
			<div class="col-xs-9">
				<table class="table table-striped ">
					<thead>
						<tr>
							<th></th>
							<th>title</th>
							<th>opinion</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |t| %>
						<tr>
							<td>
								<%= link_to user_path(t.user.id) do %>
									<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "50x50" %>
								<%end%>
							</td>
							<td>
								<%= link_to t.title, book_path(t.id) %>
							</td>
							<td><%= t.body %></td>
							<td></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>

		</div>
	</div>
<%= render "books/footer" %>

Bookers2nd/app/views/books/show.html.erb
<%= render "books/header", books: @user %>

<div class="container pl-15 pr-15">
	<p id="notice"><%= notice %></p>
	<div class="row">
		<%= render "books/sidebar", book: @book_new, user: @user %>
		<h2>Book detail</h2>
		<div class="col-xs-9">
			<table class="table table-striped ">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<%= link_to(user_path(@book.user.id)) do |user| %>
								<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
								<br><%= @book.user.name %>
							<% end %>
						</td>
						<td>
							<%= link_to @book.title, book_path(@book.id) %>
						</td>
						<td><%= @book.body %></td>
						<% if @book.user == current_user %>
						<td ><%= link_to "Edit", edit_book_path(@book.id), class: "btn-sm btn-success" %></td>
						<td> <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm"=> "Are You Sure?", class: "btn-sm btn-danger" %> </td>
						<%end%>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<%= render "books/footer" %>